apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: radionet

#secretGenerator:
#- name: radionetdb-backup-secret
#  files:
#  - radionetdb-backup-secret.conf

generatorOptions:
  disableNameSuffixHash: true

resources:
- radionetdb16-cr.yaml