apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  labels:
    argocd.argoproj.io/instance: radionetdb
  name: radionetdb
  namespace: radionet
spec:
  postgresVersion: 16
  postGISVersion: "3.3"
  backups:
    pgbackrest:
      manual:
        repoName: repo1
        options:
         - --type=full --stop-auto
      configuration:
      - secret:
          name: radionetdb-backup-secret
      global:
        repo1-path: /pgbackrest/radionetdb/repo1
        repo1-retention-full: "1"
        repo1-retention-full-type: time
        repo1-retention-diff: "6"
      repos:
      - name: repo1
        azure:
          container: dekberaddprodbck
        schedules:
          full: "0 2 * * 6"
          differential: "0 2 * * 0-5"
  instances:
    - affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: node
                    operator: In
                    values:
                      - dbruntime
              weight: 1
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster: hippo-ha
                    postgres-operator.crunchydata.com/instance-set: pgha1
                topologyKey: kubernetes.io/hostname
              weight: 1
      tolerations:
        - effect: NoSchedule
          key: node
          operator: Equal
          value: dbruntime
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 256Gi
        storageClassName: managed-csi-zrs
      name: radionetdb
      replicas: 2
      resources:
        requests:
          cpu: 500m
          memory: 4Gi
        limits:
          cpu: 3M
          memory: 12.5Gi
  service:
    type: LoadBalancer
    metadata:
     annotations:
       service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  users:
    - name: postgres